vich_uploader:
    db_driver: orm

    mappings:
        cover_image:
            uri_prefix: /images/cover_image
            upload_destination: '%kernel.project_dir%/public/images/cover_image'
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        gallery_image:
            uri_prefix: /images/gallery_image
            upload_destination: '%kernel.project_dir%/public/images/gallery_image'
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
